import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "ar" | "en";

type LanguageContextValue = {
  language: Language;
  direction: "rtl" | "ltr";
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
};

const LANGUAGE_KEY = "pharmayemen-language";

const translations: Record<string, { ar: string; en: string }> = {
  "Sign in to continue": { ar: "سجّل الدخول للمتابعة", en: "Sign in to continue" },
  "Access to this dashboard requires authentication. Continue to launch the login flow.": { ar: "يتطلب الوصول إلى لوحة التحكم تسجيل الدخول. تابع لبدء عملية الدخول.", en: "Access to this dashboard requires authentication. Continue to launch the login flow." },
  "Sign in": { ar: "تسجيل الدخول", en: "Sign in" },
  "Sign out": { ar: "تسجيل الخروج", en: "Sign out" },
  "Toggle navigation": { ar: "تبديل القائمة الجانبية", en: "Toggle navigation" },
  Menu: { ar: "القائمة", en: "Menu" },
  Overview: { ar: "نظرة عامة", en: "Overview" },
  Offers: { ar: "العروض", en: "Offers" },
  Requests: { ar: "الطلبات", en: "Requests" },
  Drugs: { ar: "الأدوية", en: "Drugs" },
  Messages: { ar: "الرسائل", en: "Messages" },
  Matches: { ar: "المطابقات", en: "Matches" },
  Profile: { ar: "الملف الشخصي", en: "Profile" },
  Entities: { ar: "الجهات", en: "Entities" },
  Intelligence: { ar: "ذكاء السوق", en: "Intelligence" },
  Alternatives: { ar: "البدائل", en: "Alternatives" },
  Dashboard: { ar: "لوحة التحكم", en: "Dashboard" },
  "Get Started": { ar: "ابدأ الآن", en: "Get Started" },
  "Go to Dashboard": { ar: "الذهاب إلى لوحة التحكم", en: "Go to Dashboard" },
  "Learn More": { ar: "اعرف المزيد", en: "Learn More" },
  "Market Intelligence Platform": { ar: "منصة ذكاء السوق", en: "Market Intelligence Platform" },
  "Connecting Yemen's": { ar: "ربط منظومة", en: "Connecting Yemen's" },
  "Pharmaceutical": { ar: "الدواء في اليمن", en: "Pharmaceutical" },
  "Supply & Demand": { ar: "العرض والطلب", en: "Supply & Demand" },
  "The first intelligent marketplace linking pharmacies, hospitals, distributors, and clinics across Yemen. Match supply with demand, discover alternatives, and access real-time market intelligence.": { ar: "منصة استخبارات سوقية تربط الصيدليات والمستشفيات والموزعين والعيادات في اليمن، وتساعد على اكتشاف العرض والطلب والفائض والشح.", en: "The first intelligent marketplace linking pharmacies, hospitals, distributors, and clinics across Yemen. Match supply with demand, discover alternatives, and access real-time market intelligence." },
  Governorates: { ar: "محافظة", en: "Governorates" },
  "Drug Categories": { ar: "فئات دوائية", en: "Drug Categories" },
  "Active Matches": { ar: "مطابقات نشطة", en: "Active Matches" },
  "Market Signals": { ar: "إشارات السوق", en: "Market Signals" },
  "Real-time": { ar: "مباشرة", en: "Real-time" },
  Daily: { ar: "يومية", en: "Daily" },
  "Intelligent Pharmaceutical Marketplace": { ar: "منصة استخبارات سوق الدواء", en: "Intelligent Pharmaceutical Marketplace" },
  "Built specifically for Yemen's pharmaceutical ecosystem with features designed to address real supply chain challenges.": { ar: "مصممة لمنظومة الدواء في اليمن لمعالجة تحديات العرض والطلب وسلاسل الإمداد ببيانات قابلة للتنفيذ.", en: "Built specifically for Yemen's pharmaceutical ecosystem with features designed to address real supply chain challenges." },
  "Entity Verification": { ar: "توثيق الجهات", en: "Entity Verification" },
  "Official Drug Catalog": { ar: "الكتالوج الدوائي الرسمي", en: "Official Drug Catalog" },
  "Supply & Demand Matching": { ar: "مطابقة العرض والطلب", en: "Supply & Demand Matching" },
  "Secure Messaging": { ar: "مراسلة آمنة", en: "Secure Messaging" },
  "Market Intelligence": { ar: "ذكاء السوق", en: "Market Intelligence" },
  "Geographic Coverage": { ar: "التغطية الجغرافية", en: "Geographic Coverage" },
  "Smart Notifications": { ar: "إشعارات ذكية", en: "Smart Notifications" },
  "Drug Alternatives": { ar: "بدائل دوائية", en: "Drug Alternatives" },
  "Admin Dashboard": { ar: "لوحة المسؤول", en: "Admin Dashboard" },
  antibiotics: { ar: "مضادات حيوية", en: "Antibiotics" },
  analgesics: { ar: "مسكنات", en: "Analgesics" },
  cardiovascular: { ar: "أدوية القلب والأوعية", en: "Cardiovascular" },
  endocrine: { ar: "أدوية الغدد الصماء", en: "Endocrine" },
  gastrointestinal: { ar: "أدوية الجهاز الهضمي", en: "Gastrointestinal" },
  respiratory: { ar: "أدوية الجهاز التنفسي", en: "Respiratory" },
  antifungal: { ar: "مضادات فطريات", en: "Antifungal" },
  antiviral: { ar: "مضادات فيروسية", en: "Antiviral" },
  vitamins: { ar: "فيتامينات", en: "Vitamins" },
  neurological: { ar: "أدوية عصبية", en: "Neurological" },
  oncology: { ar: "أدوية الأورام", en: "Oncology" },
  dermatological: { ar: "أدوية جلدية", en: "Dermatological" },
  ophthalmological: { ar: "أدوية العيون", en: "Ophthalmological" },
  other: { ar: "أخرى", en: "Other" },
  "Antibiotics": { ar: "مضادات حيوية", en: "Antibiotics" },
  "Analgesics": { ar: "مسكنات", en: "Analgesics" },
  "Cardiovascular": { ar: "أدوية القلب والأوعية", en: "Cardiovascular" },
  "Endocrine": { ar: "أدوية الغدد الصماء", en: "Endocrine" },
  "Gastrointestinal": { ar: "أدوية الجهاز الهضمي", en: "Gastrointestinal" },
  "Respiratory": { ar: "أدوية الجهاز التنفسي", en: "Respiratory" },
  "Antifungal": { ar: "مضادات فطريات", en: "Antifungal" },
  "Antiviral": { ar: "مضادات فيروسية", en: "Antiviral" },
  "Vitamins": { ar: "فيتامينات", en: "Vitamins" },
  "Neurological": { ar: "أدوية عصبية", en: "Neurological" },
  "Oncology": { ar: "أدوية الأورام", en: "Oncology" },
  "Ophthalmological": { ar: "أدوية العيون", en: "Ophthalmological" },
  "Yemen Pharmaceutical Market Intelligence Platform": { ar: "منصة استخبارات سوق الدواء في اليمن", en: "Yemen Pharmaceutical Market Intelligence Platform" },
  "Connecting supply and demand across Yemen's pharmaceutical market": { ar: "ربط العرض والطلب في سوق الدواء اليمني", en: "Connecting supply and demand across Yemen's pharmaceutical market" },
  "How It Works": { ar: "كيف تعمل المنصة", en: "How It Works" },
  "Three simple steps to connect supply with demand": { ar: "ثلاث خطوات بسيطة لربط العرض بالطلب", en: "Three simple steps to connect supply with demand" },
  "Register & Verify": { ar: "سجّل ووثّق الجهة", en: "Register & Verify" },
  "Publish & Match": { ar: "انشر وطابق", en: "Publish & Match" },
  "Connect & Trade": { ar: "تواصل خارج المنصة", en: "Connect & Trade" },
  "National Essential Medicines Catalog": { ar: "الكتالوج الوطني للأدوية الأساسية", en: "National Essential Medicines Catalog" },
  "Unified records from Yemen’s 2019 and 2022 National Essential Medicines Lists": { ar: "سجلات موحّدة من قائمتي اليمن الوطنيتين للأدوية الأساسية لعامي 2019 و2022", en: "Unified records from Yemen’s 2019 and 2022 National Essential Medicines Lists" },
  Loading: { ar: "جارٍ التحميل", en: "Loading" },
  "Loading...": { ar: "جارٍ التحميل...", en: "Loading..." },
  Cancel: { ar: "إلغاء", en: "Cancel" },
  Save: { ar: "حفظ", en: "Save" },
  Submit: { ar: "إرسال", en: "Submit" },
  Close: { ar: "إغلاق", en: "Close" },
  Search: { ar: "بحث", en: "Search" },
  "All Categories": { ar: "كل الفئات", en: "All Categories" },
  Other: { ar: "أخرى", en: "Other" },
  Medicines: { ar: "دواء", en: "Medicines" },
  "No entity registered. Please register first.": { ar: "لا توجد جهة مسجلة. يرجى تسجيل جهة أولاً.", en: "No entity registered. Please register first." },
  "No notifications yet": { ar: "لا توجد إشعارات بعد", en: "No notifications yet" },
  "No messages yet. Start the conversation.": { ar: "لا توجد رسائل بعد. ابدأ المحادثة.", en: "No messages yet. Start the conversation." },
  "No conversations yet": { ar: "لا توجد محادثات بعد", en: "No conversations yet" },
  "No offers yet": { ar: "لا توجد عروض بعد", en: "No offers yet" },
  "No requests yet": { ar: "لا توجد طلبات بعد", en: "No requests yet" },
  "No active offers found": { ar: "لم يتم العثور على عروض نشطة", en: "No active offers found" },
  "No open requests found": { ar: "لم يتم العثور على طلبات مفتوحة", en: "No open requests found" },
  "Your activity alerts and updates": { ar: "تنبيهات نشاطك وتحديثاته", en: "Your activity alerts and updates" },
  "Register Your Entity": { ar: "سجّل جهتك", en: "Register Your Entity" },
  "Register your pharmacy, hospital, distributor, or clinic": { ar: "سجّل صيدليتك أو مستشفاك أو موزعك أو عيادتك", en: "Register your pharmacy, hospital, distributor, or clinic" },
  "Entity Registration": { ar: "تسجيل جهة", en: "Entity Registration" },
  "Entity Verified": { ar: "تم توثيق الجهة", en: "Entity Verified" },
  "Pending Verification": { ar: "بانتظار التوثيق", en: "Pending Verification" },
  "Your registration is being reviewed by an administrator.": { ar: "تتم مراجعة تسجيلك من قبل المسؤول.", en: "Your registration is being reviewed by an administrator." },
  "Create New Offer": { ar: "إنشاء عرض جديد", en: "Create New Offer" },
  "Create New Request": { ar: "إنشاء طلب جديد", en: "Create New Request" },
  "Demand requests in the marketplace": { ar: "طلبات الطلب في السوق", en: "Demand requests in the marketplace" },
  "Supply offerings in the marketplace": { ar: "عروض التوريد في السوق", en: "Supply offerings in the marketplace" },
  Quantity: { ar: "الكمية", en: "Quantity" },
  Unit: { ar: "الوحدة", en: "Unit" },
  Urgency: { ar: "درجة الاستعجال", en: "Urgency" },
  Low: { ar: "منخفض", en: "Low" },
  Medium: { ar: "متوسط", en: "Medium" },
  High: { ar: "مرتفع", en: "High" },
  Critical: { ar: "حرج", en: "Critical" },
  "Select Drug": { ar: "اختر الدواء", en: "Select Drug" },
  "Search drugs...": { ar: "ابحث عن دواء...", en: "Search drugs..." },
  "Drug Name": { ar: "اسم الدواء", en: "Drug Name" },
  "Name": { ar: "الاسم", en: "Name" },
  "Type": { ar: "النوع", en: "Type" },
  "Pharmacy": { ar: "صيدلية", en: "Pharmacy" },
  "Hospital": { ar: "مستشفى", en: "Hospital" },
  "Distributor": { ar: "موزع", en: "Distributor" },
  "Clinic": { ar: "عيادة", en: "Clinic" },
  "Region": { ar: "الإقليم", en: "Region" },
  "Governorate": { ar: "المحافظة", en: "Governorate" },
  "City": { ar: "المدينة", en: "City" },
  "Address": { ar: "العنوان", en: "Address" },
  "Contact Person": { ar: "جهة الاتصال", en: "Contact Person" },
  Phone: { ar: "الهاتف", en: "Phone" },
  "License Number": { ar: "رقم الترخيص", en: "License Number" },
  "Welcome back": { ar: "أهلاً بك", en: "Welcome back" },
  "Active Offers": { ar: "العروض النشطة", en: "Active Offers" },
  "Open Requests": { ar: "الطلبات المفتوحة", en: "Open Requests" },
  "New Offer": { ar: "عرض جديد", en: "New Offer" },
  "Official Catalog": { ar: "الكتالوج الرسمي", en: "Official Catalog" },
  "Free Text": { ar: "إدخال حر", en: "Free Text" },
  "Selected drug": { ar: "الدواء المحدد", en: "Selected drug" },
  "Enter drug name (will not be added to official catalog)": { ar: "أدخل اسم الدواء (لن يُضاف إلى الكتالوج الرسمي)", en: "Enter drug name (will not be added to official catalog)" },
  Boxes: { ar: "علب", en: "Boxes" },
  Strips: { ar: "شرائط", en: "Strips" },
  Vials: { ar: "قوارير", en: "Vials" },
  Bottles: { ar: "زجاجات", en: "Bottles" },
  Ampoules: { ar: "أمبولات", en: "Ampoules" },
  Packs: { ar: "عبوات", en: "Packs" },
  "Create Offer": { ar: "إنشاء العرض", en: "Create Offer" },
  "Quantity must be at least 1": { ar: "يجب أن تكون الكمية واحداً على الأقل", en: "Quantity must be at least 1" },
  "Offer created successfully": { ar: "تم إنشاء العرض بنجاح", en: "Offer created successfully" },
  "Unable to create offer": { ar: "تعذر إنشاء العرض", en: "Unable to create offer" },
  "Unable to load offers. Please retry.": { ar: "تعذر تحميل العروض. يرجى إعادة المحاولة.", en: "Unable to load offers. Please retry." },
  Retry: { ar: "إعادة المحاولة", en: "Retry" },
  "Offer closed": { ar: "تم إغلاق العرض", en: "Offer closed" },
  Unlisted: { ar: "غير مدرج", en: "Unlisted" },
  Expires: { ar: "ينتهي في", en: "Expires" },
  "New Request": { ar: "طلب جديد", en: "New Request" },
  "Request created successfully": { ar: "تم إنشاء الطلب بنجاح", en: "Request created successfully" },
  "Request closed": { ar: "تم إغلاق الطلب", en: "Request closed" },
  "Create Request": { ar: "إنشاء الطلب", en: "Create Request" },
  "Unable to create request": { ar: "تعذر إنشاء الطلب", en: "Unable to create request" },
  Found: { ar: "تم العثور على", en: "Found" },
  "potential match": { ar: "مطابقة محتملة", en: "potential match" },
  "potential matches": { ar: "مطابقات محتملة", en: "potential matches" },
  "Match accepted - conversation started": { ar: "تم قبول المطابقة وبدء المحادثة", en: "Match accepted - conversation started" },
  "Match rejected": { ar: "تم رفض المطابقة", en: "Match rejected" },
  Unknown: { ar: "غير معروف", en: "Unknown" },
  "Automatic supply-demand matching by drug name": { ar: "مطابقة تلقائية للعرض والطلب حسب اسم الدواء", en: "Automatic supply-demand matching by drug name" },
  "How Matching Works": { ar: "كيف تعمل المطابقة", en: "How Matching Works" },
  "Matches are created automatically when a drug name matches between your offers and requests, regardless of quantity. Location and urgency add bonus points to the match score.": { ar: "تُنشأ المطابقات تلقائياً عند تطابق اسم الدواء بين عروضك وطلباتك، بغض النظر عن الكمية. وتضيف المنطقة ودرجة الاستعجال نقاطاً إضافية إلى نتيجة المطابقة.", en: "Matches are created automatically when a drug name matches between your offers and requests, regardless of quantity. Location and urgency add bonus points to the match score." },
  "My Offers": { ar: "عروضي", en: "My Offers" },
  "My Requests": { ar: "طلباتي", en: "My Requests" },
  "Select an Offer to View Matches": { ar: "اختر عرضاً لعرض المطابقات", en: "Select an Offer to View Matches" },
  "Select a Request to View Matches": { ar: "اختر طلباً لعرض المطابقات", en: "Select a Request to View Matches" },
  "Find Matches": { ar: "ابحث عن المطابقات", en: "Find Matches" },
  "No active offers yet. Create one to find matches.": { ar: "لا توجد عروض نشطة بعد. أنشئ عرضاً للعثور على مطابقات.", en: "No active offers yet. Create one to find matches." },
  "No open requests yet. Create one to find matches.": { ar: "لا توجد طلبات مفتوحة بعد. أنشئ طلباً للعثور على مطابقات.", en: "No open requests yet. Create one to find matches." },
  "No matches found yet. Create more requests to find matches.": { ar: "لم يتم العثور على مطابقات بعد. أنشئ المزيد من الطلبات للعثور على مطابقات.", en: "No matches found yet. Create more requests to find matches." },
  "No matches found yet. Other entities need to create offers for this drug.": { ar: "لم يتم العثور على مطابقات بعد. تحتاج الجهات الأخرى إلى إنشاء عروض لهذا الدواء.", en: "No matches found yet. Other entities need to create offers for this drug." },
  Requested: { ar: "المطلوب", en: "Requested" },
  Available: { ar: "المتاح", en: "Available" },
  Match: { ar: "مطابقة", en: "Match" },
  match: { ar: "مطابقة", en: "match" },
  matches: { ar: "مطابقات", en: "matches" },
  "Drug Match": { ar: "مطابقة الدواء", en: "Drug Match" },
  Location: { ar: "الموقع", en: "Location" },
  Total: { ar: "الإجمالي", en: "Total" },
  Accept: { ar: "قبول", en: "Accept" },
  Reject: { ar: "رفض", en: "Reject" },
  Accepted: { ar: "مقبولة", en: "Accepted" },
  Rejected: { ar: "مرفوضة", en: "Rejected" },
  "Entity verified": { ar: "تم توثيق الجهة", en: "Entity verified" },
  "Entity suspended": { ar: "تم تعليق الجهة", en: "Entity suspended" },
  "Unable to update entity": { ar: "تعذر تحديث الجهة", en: "Unable to update entity" },
  "Review and approve entity registrations": { ar: "مراجعة طلبات تسجيل الجهات والموافقة عليها", en: "Review and approve entity registrations" },
  "No pending entities": { ar: "لا توجد جهات بانتظار التوثيق", en: "No pending entities" },
  "No phone": { ar: "لا يوجد هاتف", en: "No phone" },
  "No address": { ar: "لا يوجد عنوان", en: "No address" },
  License: { ar: "الترخيص", en: "License" },
  Approve: { ar: "موافقة", en: "Approve" },
  Suspend: { ar: "تعليق", en: "Suspend" },
  "Unified national essential medicines catalog for Yemen": { ar: "الكتالوج الوطني الموحد للأدوية الأساسية في اليمن", en: "Unified national essential medicines catalog for Yemen" },
  "Market signals and analysis": { ar: "إشارات السوق وتحليلاته", en: "Market signals and analysis" },
  "No market signals yet": { ar: "لا توجد إشارات سوق بعد", en: "No market signals yet" },
  Shortage: { ar: "شح", en: "Shortage" },
  Surplus: { ar: "فائض", en: "Surplus" },
  "Hidden Inventory": { ar: "مخزون غير مرئي", en: "Hidden Inventory" },
  "Price Anomaly": { ar: "تغير سعري غير معتاد", en: "Price Anomaly" },
  "Trend Shift": { ar: "تحول في الاتجاه", en: "Trend Shift" },
  New: { ar: "جديد", en: "New" },
  Acknowledged: { ar: "تمت المراجعة", en: "Acknowledged" },
  Dismissed: { ar: "مستبعد", en: "Dismissed" },
  Resolved: { ar: "تم الحل", en: "Resolved" },
  Confidence: { ar: "درجة الثقة", en: "Confidence" },
  "Chat with matched entities": { ar: "تواصل مع الجهات المطابقة", en: "Chat with matched entities" },
  Conversations: { ar: "المحادثات", en: "Conversations" },
  "Contact revealed": { ar: "تم إظهار بيانات الاتصال", en: "Contact revealed" },
  "Contact hidden": { ar: "بيانات الاتصال مخفية", en: "Contact hidden" },
  "Contact Revealed": { ar: "تم إظهار بيانات الاتصال", en: "Contact Revealed" },
  "Reveal Contact": { ar: "إظهار بيانات الاتصال", en: "Reveal Contact" },
  "Contact info shared": { ar: "تمت مشاركة بيانات الاتصال", en: "Contact info shared" },
  "Loading messages...": { ar: "جارٍ تحميل الرسائل...", en: "Loading messages..." },
  "Type a message...": { ar: "اكتب رسالة...", en: "Type a message..." },
  "Select a conversation to start messaging": { ar: "اختر محادثة لبدء المراسلة", en: "Select a conversation to start messaging" },
  "Entity Profile": { ar: "ملف الجهة", en: "Entity Profile" },
  "Your organization details": { ar: "تفاصيل جهتك", en: "Your organization details" },
  "Organization Details": { ar: "تفاصيل الجهة", en: "Organization Details" },
  Status: { ar: "الحالة", en: "Status" },
  verified: { ar: "موثقة", en: "verified" },
  pending: { ar: "قيد المراجعة", en: "pending" },
  suspended: { ar: "معلّقة", en: "suspended" },
  "Link and manage substitute drugs by active ingredient or therapeutic category": { ar: "اربط وأدر البدائل حسب المادة الفعالة أو الفئة العلاجية", en: "Link and manage substitute drugs by active ingredient or therapeutic category" },
  "Link Alternative Drug": { ar: "ربط دواء بديل", en: "Link Alternative Drug" },
  "Source Drug": { ar: "الدواء المصدر", en: "Source Drug" },
  "Search for source drug...": { ar: "ابحث عن الدواء المصدر...", en: "Search for source drug..." },
  "Alternative Drug": { ar: "الدواء البديل", en: "Alternative Drug" },
  "Search for alternative drug...": { ar: "ابحث عن الدواء البديل...", en: "Search for alternative drug..." },
  "Link Alternative": { ar: "ربط البديل", en: "Link Alternative" },
  "View & Manage Existing Alternatives": { ar: "عرض وإدارة البدائل الحالية", en: "View & Manage Existing Alternatives" },
  "Select Drug to View Alternatives": { ar: "اختر دواءً لعرض بدائله", en: "Select Drug to View Alternatives" },
  "Search for a drug...": { ar: "ابحث عن دواء...", en: "Search for a drug..." },
  "Alternatives for": { ar: "البدائل لـ", en: "Alternatives for" },
  "No alternatives linked for this drug": { ar: "لا توجد بدائل مرتبطة بهذا الدواء", en: "No alternatives linked for this drug" },
  "Alternative linked successfully": { ar: "تم ربط البديل بنجاح", en: "Alternative linked successfully" },
  "Alternative unlinked": { ar: "تم إلغاء ربط البديل", en: "Alternative unlinked" },
  "Unable to link alternative": { ar: "تعذر ربط البديل", en: "Unable to link alternative" },
  Notifications: { ar: "الإشعارات", en: "Notifications" },
  "Mark All Read": { ar: "تحديد الكل كمقروء", en: "Mark All Read" },
  Unread: { ar: "غير مقروء", en: "Unread" },
  "Mark Read": { ar: "تحديد كمقروء", en: "Mark Read" },
  "All notifications marked as read": { ar: "تم تحديد جميع الإشعارات كمقروءة", en: "All notifications marked as read" },
  "New Match": { ar: "مطابقة جديدة", en: "New Match" },
  "New Message": { ar: "رسالة جديدة", en: "New Message" },
  "Market Signal": { ar: "إشارة سوق", en: "Market Signal" },
  "Entity Approved": { ar: "تم اعتماد الجهة", en: "Entity Approved" },
  "Offer Matched": { ar: "تمت مطابقة العرض", en: "Offer Matched" },
  "Request Matched": { ar: "تمت مطابقة الطلب", en: "Request Matched" },
  "Offer Expired": { ar: "انتهت صلاحية العرض", en: "Offer Expired" },
  "Request Expired": { ar: "انتهت صلاحية الطلب", en: "Request Expired" },
  "Registration submitted for review": { ar: "تم إرسال التسجيل للمراجعة", en: "Registration submitted for review" },
  "Unable to submit registration": { ar: "تعذر إرسال التسجيل", en: "Unable to submit registration" },
  "is verified and active.": { ar: "موثقة ونشطة.", en: "is verified and active." },
  "Entity Status": { ar: "حالة الجهة", en: "Entity Status" },
  "Registration Form": { ar: "نموذج التسجيل", en: "Registration Form" },
  "Entity Name": { ar: "اسم الجهة", en: "Entity Name" },
  "e.g., Al-Amal Pharmacy": { ar: "مثال: صيدلية الأمل", en: "e.g., Al-Amal Pharmacy" },
  "Select type": { ar: "اختر النوع", en: "Select type" },
  Optional: { ar: "اختياري", en: "Optional" },
  "Select region": { ar: "اختر الإقليم", en: "Select region" },
  "Select governorate": { ar: "اختر المحافظة", en: "Select governorate" },
  "Select city": { ar: "اختر المدينة", en: "Select city" },
  "Submit Registration": { ar: "إرسال التسجيل", en: "Submit Registration" },
  "Sign In": { ar: "تسجيل الدخول", en: "Sign In" },
  "Please register your entity to access all features": { ar: "يرجى تسجيل جهتك للوصول إلى جميع الميزات", en: "Please register your entity to access all features" },
  "Register as a pharmacy, hospital, distributor, or clinic with admin approval and role-based access control.": { ar: "سجّل صيدلية أو مستشفى أو موزعاً أو عيادة مع اعتماد المسؤول وصلاحيات مناسبة.", en: "Register as a pharmacy, hospital, distributor, or clinic with admin approval and role-based access control." },
  "Full-text search by brand name, generic name, and active ingredient. Free-text entries for unlisted drugs.": { ar: "بحث نصي شامل بالاسم التجاري والعلمي والمادة الفعالة، مع إدخال حر للأدوية غير المدرجة.", en: "Full-text search by brand name, generic name, and active ingredient. Free-text entries for unlisted drugs." },
  "Publish offers or requests and let our intelligent matching engine connect you with the right counterpart.": { ar: "انشر عروضك أو طلباتك ودع محرك المطابقة الذكي يربطك بالطرف المناسب.", en: "Publish offers or requests and let our intelligent matching engine connect you with the right counterpart." },
  "Chat with matched entities. Contact details are only revealed after mutual consent from both parties.": { ar: "تحدث مع الجهات المطابقة، ولا تظهر بيانات الاتصال إلا بعد موافقة الطرفين.", en: "Chat with matched entities. Contact details are only revealed after mutual consent from both parties." },
  "Regional shortage and surplus indices, most-demanded drugs, and supply-demand trend analysis.": { ar: "مؤشرات الشح والفائض حسب المنطقة، والأدوية الأكثر طلباً، وتحليل اتجاهات العرض والطلب.", en: "Regional shortage and surplus indices, most-demanded drugs, and supply-demand trend analysis." },
  "Pre-seeded with Yemen's 22 governorates and regions. Location-based filtering and matching across the country.": { ar: "بيانات أولية لمحافظات اليمن الـ22 وأقاليمه، مع تصفية ومطابقة حسب الموقع في جميع أنحاء البلاد.", en: "Pre-seeded with Yemen's 22 governorates and regions. Location-based filtering and matching across the country." },
  "In-app and email alerts for new matches, messages, and market signals affecting your region.": { ar: "تنبيهات داخل المنصة وعبر البريد للمطابقات والرسائل وإشارات السوق التي تؤثر في منطقتك.", en: "In-app and email alerts for new matches, messages, and market signals affecting your region." },
  "Link substitute drugs by active ingredient or therapeutic category for better matching.": { ar: "اربط الأدوية البديلة حسب المادة الفعالة أو الفئة العلاجية لتحسين المطابقة.", en: "Link substitute drugs by active ingredient or therapeutic category for better matching." },
  "Entity verification queue, drug catalog management, and platform-wide market signal review.": { ar: "قائمة توثيق الجهات وإدارة الكتالوج الدوائي ومراجعة إشارات السوق على مستوى المنصة.", en: "Entity verification queue, drug catalog management, and platform-wide market signal review." },
  "Create your entity profile as a pharmacy, hospital, distributor, or clinic. Admin verification ensures trust.": { ar: "أنشئ ملف جهتك كصيدلية أو مستشفى أو موزع أو عيادة. ويضمن توثيق المسؤول الثقة.", en: "Create your entity profile as a pharmacy, hospital, distributor, or clinic. Admin verification ensures trust." },
  "Post your offers or requests. Our matching engine scores pairs by drug, location, urgency, and quantity.": { ar: "انشر عروضك أو طلباتك. ويقيّم محرك المطابقة الأزواج حسب الدواء والموقع والاستعجال والكمية.", en: "Post your offers or requests. Our matching engine scores pairs by drug, location, urgency, and quantity." },
  "Chat with matches, reveal contact info by mutual consent, and complete the transaction outside the platform.": { ar: "تحدث مع المطابقات، وأظهر بيانات الاتصال بموافقة متبادلة، وأكمل التعامل خارج المنصة.", en: "Chat with matches, reveal contact info by mutual consent, and complete the transaction outside the platform." },
};

const reverseTranslations = Object.fromEntries(
  Object.entries(translations).map(([key, values]) => [values.ar, key]),
);

function readInitialLanguage(): Language {
  if (typeof window === "undefined") return "ar";
  return window.localStorage.getItem(LANGUAGE_KEY) === "en" ? "en" : "ar";
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(readInitialLanguage);
  const direction = language === "ar" ? "rtl" : "ltr";

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    window.localStorage.setItem(LANGUAGE_KEY, next);
  };

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    document.body.dataset.language = language;
  }, [direction, language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    direction,
    setLanguage,
    toggleLanguage: () => setLanguage(language === "ar" ? "en" : "ar"),
    t: (key, fallback) => translations[key]?.[language] ?? fallback ?? key,
  }), [direction, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export function translateKnownText(value: string, language: Language): string {
  const normalized = value.replace(/\s+/g, " ").trim();
  if (language === "en") return reverseTranslations[normalized] ?? value;
  return translations[normalized]?.ar ?? value;
}
